---
version: "3"
services:

  redis:
    image: redis:latest
    ports:
      - "6379"
    networks:
      - default

  toolbox:
    build: ../toolbox
    networks:
      - default

  haproxy:
    image: haproxy:1.9
    ports:
      - "6380:6380"
    environment:
      REDIS_HOST: redis 
      REDIS_PORT: "6379"
      REDIS_PROXY_PORT: "6380"
    networks:
      - default
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  default:
