---
version: "3"
services:

  nginx:
    image: nginx:latest
    ports:
      - "80"
    networks:
      - default

  toolbox:
    build: ../toolbox
    networks:
      - default

  haproxy:
    image: haproxy:1.9
    ports:
      - "8000:8000"
    environment:
      NGINX_HOST: nginx
      NGINX_PORT: "80"
      NGINX_PROXY_PORT: "8000"
    networks:
      - default
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
  default:
